import jQuery from "jquery";
import bootstrap from "bootstrap";
import "datatables.net-bs4/js/dataTables.bootstrap4";
import "datatables.net/js/jquery.dataTables";
import "./bootstrappers/datatables.js";
require("block-ui");
require("bootstrap-select");
require("flatpickr");
window.$ = jQuery;
window.jQuery = jQuery;
window.Noty = require("noty");
require("./bootstrappers/global-hooks.js");
